### ISSUE TITLE
Question: Deplyoying two instances of freeDiameterd with same Diam-Id and Realm

### ISSUE THREAD

**Issue by atari83** [freeDiameter/freeDiameter#11]
Hello!

I've this plan to deploy two instances of freeDiameterd on separated machines (different IP of-course) acting as diameter servers (proxy/relay) in the network. The goal is to let external diameter clients to connect to both of proxy servers and load-balance their traffic on both of them.

Although I didnt test this yet, but the external clients brought up this requirement that in order to be able to connect both proxy servers and load-share the traffic I've to use and configure same Daim-Id and Realm on both diameter servers.

In same time I've couple of diameter clients in my network (behind the diameter proxies), So I wonder when I specify such configuration for diameter clients, is it going to work:

```
ConnectPeer = "relay.freediameter.net" { ConnectTo = "192.168.1.50"; };
ConnectPeer = "relay.freediameter.net" { ConnectTo = "192.168.1.60"; };
```

To be more specific, does diameter clients in my network is going to send the response back to same diameter proxy server which delivered the request to client ? Or it would be random ? what should i be expected ?! I'm asking this because from diameter client point-of-view there will be two similar nodes with same diam-id / realm. 

At the end, I was just curious to know your experiences and inputs for such requirement, and to know if it is normal and good practice to deploy with this design ?

Thanks

**Comment by atari83** [comment]
First update:

I've tested this config on the clients (behind the relay servers):
```
ConnectPeer = "relay.freediameter.net" { ConnectTo = "192.168.1.50"; };
ConnectPeer = "relay.freediameter.net" { ConnectTo = "192.168.1.60"; };

```
Basically, it failed because when freediameter daemon started reading the config it says there are duplicated host names in the config file (pointed to 'relay.freediameter.net').

**Comment by 0-wiz-0** [comment]
A Diameter Identity is usually the DNS hostname of the machine.
Often, this is not actually done this way (and it is supported by freeDiameter to use arbitrary names).
However, the Diameter Identity must be unique, otherwise routing messages correctly will be next to impossible. (This is one reason for the above.)
I don't see the requirement by the external client as reasonable. They could just set Destination-Realm and just leave the  Destination-Host empty.

**Comment by atari83** [comment]
Thank you Thomas, It totally makes sense.
To be honest, the requirement that they've brought up is also odd to me as well. I'm not sure but maybe they've some difficulties for configuring different diam-ids at their end (specially, for connection binding stage and CER/CEA).

Anyhow, I think I'm going to hold another meeting with them for clarification.

Thank you again.
