### ISSUE TITLE
Bad DWA message causes freeDiameterd to crash

### ISSUE THREAD

**Issue by atari83** [freeDiameter/freeDiameter#15]
Hello!
I've Diameter node in network which sends wrong DWA messages to my node (running freeDiameterd). According to msg-dump what i can understand is that they're using wrong End-To-End Identifier in their DWA (not sure it is the main reason). However it is not my concern, my concern is that such messages will cause freeDiameterd process to crash for some reason.

```

17:50:21  NOTI   SND to 'extra1-cl01.svcd.zoneula.co':
17:50:21  NOTI        'Device-Watchdog-Request'
17:50:21  NOTI          Version: 0x01
17:50:21  NOTI          Length: 96
17:50:21  NOTI          Flags: 0x80 (R---)
17:50:21  NOTI          Command Code: 280
17:50:21  NOTI          ApplicationId: 0
17:50:21  NOTI          Hop-by-Hop Identifier: 0x6F9DD24C
17:50:21  NOTI          End-to-End Identifier: 0xC0763DED
17:50:21  NOTI           {internal data}: src:(nil)(0) rwb:0x0 rt:0 cb:0x0,0x0(0x0) qry:0x0 asso:0 sess:0x0
17:50:21  NOTI           AVP: 'Origin-Host'(264) l=34 f=-M val="proxy001.loc.freediamd.net"
17:50:21  NOTI           AVP: 'Origin-Realm'(296) l=25 f=-M val="loc.freediamd.net"
17:50:21  NOTI           AVP: 'Origin-State-Id'(278) l=12 f=-M val=1644329991 (0x62027c07)

17:50:21  NOTI   RCV from 'extra1-cl01.svcd.zoneula.co':
17:50:21  NOTI        'Device-Watchdog-Answer'
17:50:21  NOTI          Version: 0x01
17:50:21  NOTI          Length: 92
17:50:21  NOTI          Flags: 0x40 (-P--)
17:50:21  NOTI          Command Code: 280
17:50:21  NOTI          ApplicationId: 0
17:50:21  NOTI          Hop-by-Hop Identifier: 0x6F9DD24C
17:50:21  NOTI          End-to-End Identifier: 0x6F9DD24C
17:50:21  NOTI           {internal data}: src:extra1-cl01.svcd.zoneula.co(27) rwb:0x0 rt:0 cb:0x0,0x0(0x0) qry:0x839004140 asso:0 sess:0x0
17:50:21  NOTI           AVP: 'Result-Code'(268) l=12 f=-M val='DIAMETER_SUCCESS' (2001 (0x7d1))
17:50:21  NOTI           AVP: 'Origin-Host'(264) l=35 f=-M val="extra1-cl01.svcd.zoneula.co"
17:50:21  NOTI           AVP: 'Origin-Realm'(296) l=23 f=-M val="svcd.zoneula.co"

17:50:21  ERROR  ERROR: Invalid parameter '(diamid && diamidlen && peer)', 22
17:50:21  ERROR  ERROR: in '((fd_peer_getbyid( qry_src, qry_src_len, 0, (void *) &peer )))' :   Invalid argument
17:50:21  ERROR  ERROR: in '((*action_cb)(msg))' :      Invalid argument

```

**Comment by atari83** [comment]
Hello !

I think I found the issue !!
Let me first give you the update about E2E Identifier, The peer node actually now resolved that problem and now H2H and E2E identifiers are Okey. However, we've re-test the service and failed with same log.

Then I noticed that, they're using `Flags: 0x40 (-P--)` in their DWA message header. I think this is wrong and it has to be set with 0x0. (I hope my finding is correct here ..)

We plan to test it again with peer node to see if the problem is resolved or not. I'll update later.

My question is if this is the root-cause, can we fix the code to see if the DWA is not ok simply just drop the peer and not affect the whole service ?

**Comment by atari83** [comment]
Hello !

Peer node has fixed the wrong Flag in DWA message, and the service is ok now.
With this I can confirm that the root-cause for freeDiameterd crash was receiving wrong Flag (0x40) in DWA message.

**Comment by sdecugis** [comment]
Thank you for the confirmation. Indeed a bad DWA should not make the instance crash at all.
I have added a patch to protect against this case, could you give it a try ?

**Comment by atari83** [comment]
Thank you Sebastien,
The problematic peer (that was sending wrong DWA msgs) has already fixed their end. But I'll recompile the the daemon with the patch anyway. I might catch similar case in future, or even ask them to revert their changes to see how it goes ^^

Thanks again.

**Comment by atari83** [comment]
I'll close this thread for now and raise new one if I faced similar case.
