### ISSUE TITLE
Request life-time in queue

### ISSUE THREAD

**Issue by atari83** [freeDiameter/freeDiameter#20]
Hello !

I've setup the freeDiameter to provide relay in the network. One of issues that I've is that sometimes the nodes behind the freeDiameterd relay server are not responsive and they'd response each request sometimes more than 5~ seconds.
Meanwhile, the rate of incoming requests is much faster.

While I tried to make the Local / Incoming / Outgoing queues bigger in config file, still it doesnt help that much. I was thinking if there is anyway to control over pending requests so I could invalidate pending requests after certain amount of time (ex: 2 seconds)

Correct me if I'm wrong but I think such configuration is not existed for now. So could somebody point me to the code so i could make changes and recompile ?

Thanks

**Comment by 0-wiz-0** [comment]
I think you can use the `rt_busypeers` extension for your purpose.

Please make yourself familiar with all the extensions, thanks.

**Comment by atari83** [comment]
Thank you Thomas, It was great help.
Sure, I need to to review all existing extensions before posting ^^ sorry about that.
