### ISSUE TITLE
Need recommendation on configure freeDiameterd daemon params

### ISSUE THREAD

**Issue by atari83** [freeDiameter/freeDiameter#21]
Hello!
I'm trying to figure out what is the best setup I could make for freeDiameterd daemon for serving traffics in my network.
So, my scenario is: 
There are 4 nodes (upstream) generating traffics toward my freeDiameterd node and I've to relay them on a node (downstream). Each upstream node is generating around 50 requests per second (TPS: ~50) and the downstream node has visible delay for sending in replies (around 5secs).

My server has 16 CPU cores with 32GB RAM
and here is my current configuration:

1- Document mentioned that "ThreadsPerServer" is only being used for binding new peers at a moment, so this should be more than enough:
`ThreadsPerServer = 5;`

2- About "AppServThreads", documentation says it is the number of thread for processing incoming requests (Global Incoming Queue, I guess ?!), I configured it as highest value possible:
`AppServThreads = 16;`

3- About "RoutingInThreads", documentation says it is the number of threads for routing incoming requests:
`RoutingInThreads = 4;`

4- About "RoutingOutThreads", documentation says it is the number of threads for routing outgoing requests:
`RoutingOutThreads = 4;`

5- About "IncomingQueueLimit", The Incoming queue, the incoming requests waited for being process. (I was scared, so just gave it high value):
`IncomingQueueLimit = 37500;`

6- About "OutgoingQueueLimit", The Outgoing queue, the requests waited for being sent. (I was scared, so just gave it high value):
`OutgoingQueueLimit = 62500;`

7- About "LocalQueueLimit", The Local queue, the requests for being processed locally. (I was scared, so just gave it high value):
`LocalQueueLimit = 50000;`

I managed for arranging a Test-Run to see whats the feedback. queue statistics report via `dbg_monitor` :

a)

```
Global 'Local delivery': cur:0/50000, h:50000, T:2641428 in 2523146.756992s (1.05items/s), blocked:6.357965s, last processing:0.000126s
Global 'Total received': cur:0/37500, h:37500, T:4891544 in 2766479.593695s (1.77items/s), blocked:168.403045s, last processing:0.000038s
Global 'Total sending': cur:0/62500, h:62500, T:4891542 in 6978293.551586s (0.70items/s), blocked:1360.040619s, last processing:0.000032s
```

- I'm not sure why all Global queues hit-times are the same as the queue-max size (maybe network burst traffic at beginning), however the Current objects in Global Queues is zero, sooo I should not be worry right ?.
- Also as I see, The Outgoing queue blocked time has huge difference comparing to other queues (that being said, the last processing time was actually equal to other queues)

b)

One of Upstream peer stats:
```
{peer}(@0x843010f00): WIFI_GW_01 [STATE_OPEN, cnt:0sr,2174pa] rlm:peyto.net ['data@peyto.net' 0]
'Events, incl. recept'@'WIFI_GW_01': cur:0/0, h:10662, T:760267 in 227943.260560s (3.34items/s), blocked:0.697601s, last processing:0.000059s
'Outgoing'@'WIFI_GW_01': cur:0/5, h:5, T:758091 in 63.771901s (11887.54items/s), blocked:7.304450s, last processing:0.000030s
```

The Downstream peer stats:
```
{peer}(@0x801225780): ENTCHG_GW [STATE_OPEN, cnt:7020sr,0pa] rlm:peyto.net ['chrg' 1]
'Events, incl. recept'@'ENTCHG_GW': cur:0/0, h:56, T:1880905 in 261.055343s (7205.00items/s), blocked:1.388572s, last processing:0.000045s
'Outgoing'@'ENTCHG_GW': cur:0/5, h:5, T:1887923 in 101.988487s (18511.14items/s), blocked:1.816708s, last processing:0.000028s
```

- Upstream nodes have alot of requests pending for answers (pa 2174, because the downstream is slow)
- Downstream node has alot of requests to feedback (sr 7020, we know why!)
- Again the blocked time for Outgoing queue on Upstream node much bigger than its incoming queue (I guess because of the difference between rate of requests and answers, right ?! )
- Also I dont know why the Events Queue size for each peer is zero .. and what does it mean ..
- And why the Outgoing Queue size for each peer is only 5 .. Is it ok ?!
- The queue hit-number (peak) for Upstream node is around 10662, I dont understand what queue it is pointed to (Global Outgoing Queue ?!)

It was my observations, So in general I see Outgoing queues are quite busier than other queues and I've some pending requests between these nodes. For slow responses I'm going to use `rt_busypeer` to help myself to forget about state of pending requests and just feedback the error to upstream after certain of time.

I need your overall recommendations and perspective about this Test-Run, and what I can do better to make freeDiameterd daemon to perform better. (please assume the connectivity and architecture of existing test-run and network would not change in future)

Thanks.

**Comment by sdecugis** [comment]
Hi, as I understand it, you have almost no processing on these relay peers. You have an incoming rate of 200 messages per seconds only (4 * 50) that are relayed to your downstream peer, then answers coming back with a 5 seconds delay. So the relay needs to keep a cache of ~ 1000 messages that are pending their response.
All these numbers seem not too challenging for a reasonable hardware configuration. I am not sure if you need to change the default configuration for the threads numbers. All the queues you show seem not filling up, so the flow of messages is faster than the rate they are coming in. 
How big is each Diameter message you are relaying on average ?

**Comment by atari83** [comment]
The incoming requests are around 700B to 1K, and the responses are about 350B

**Comment by sdecugis** [comment]
Thanks. So assuming 1K, with 1000 messages pending, you will use around 1MB of RAM to store the messages pending the answers from the downstream server. (there is actually a bit of overhead on this but not too much). This is pretty easy to manage, I see nothing to worry about, the implementation can handle quite a bigger workload than what you are planning here... I think you can keep the monitoring extension loaded for some time and keep watching the "cur" values of the different queues to see if some of them start growing, which could indicate some bottlenecks. Other than that, it looks like you are good to go.

**Comment by atari83** [comment]
Thank you Sebastien :)
I'll keep monitoring the service status for a week and feedback.

**Comment by atari83** [comment]
Its been about 5 days that re-run the service-test and as expected the daemon is handling traffics just fine. the CPU usage is barely  reach to half of a cpu-core. I don't see any sort of abnormality but an small issue about memory usage. As I'm monitoring the service I observed that there were small increase on service allocated memory (resident memory) around 1MB for each 2days of running service. It is not big deal though, I'm guessing maybe it'll be freed by OS memory laundry process.
