### ISSUE TITLE
Relaying with rt_default

### ISSUE THREAD

**Issue by nickvsnetworking** [freeDiameter/freeDiameter#31]
Hi freeDiameter team,

I'm trying to use the rt_default extension to configure FreeDiameter as a DRA,

I have 3 diameter peers defined in freeDiameter:
```
ConnectPeer = "hss.localdomain" {Realm="mnc001.mcc001.3gppnetwork.org"; ConnectTo = "127.0.0.8"; Port=3869; No_TLS; };
ConnectPeer = "hss.roaming" {Realm="mnc070.mcc901.3gppnetwork.org"; ConnectTo = "127.0.0.9"; Port=3870; No_TLS; };
ConnectPeer = "nick-pc" {Realm="mnc070.mcc901.3gppnetwork.org"; ConnectTo="172.16.41.1"; Port=3868;};
```

And I have loaded the rt_default and rt_redir extensions:
```
LoadExtension = "rt_redirect.fdx";
LoadExtension = "rt_default.fdx":"rt_default.conf";
```

And my rt_redirect config is about as simple as it gets, for any request route to the one peer:
`* : "hss.localdomain" += DEFAULT ;`

But unfortunately when I sent a request from Peer nick-pc, I'm not seeing it relayed to peer hss.localdomain, even though hss.localdomain is in STATE_OPEN.

Instead when I trigger a request towards FreeDiameter, I get an error indicating that freeDiameter does not have the dictionaries defined on the local instance, but I'm not expecting it to - I just need it to act as a relay.

Adding the Diameter dictionaries didn't seem to change that either.

```
12:35:27  ERROR  ERROR: in '(ret = fd_dict_search ( dict, DICT_COMMAND, (msg->msg_public.msg_flags & 0x80) ? CMD_BY_CODE_R : CMD_BY_CODE_A, &msg->msg_public.msg_code, &msg->msg_model, 95))' :	Operation not supported
12:35:27  ERROR  ERROR: in '((fd_msg_parse_dict ( object, dict, error_info )))' :	Operation not supported
12:35:27  ERROR  ERROR: in '(fd_msg_parse_rules( msg, fd_g_config->cnf_dict, &pei ))' :	Operation not supported
12:35:27  ERROR  Parsing error: 'DIAMETER_COMMAND_UNSUPPORTED' for the following message received from '<local>':
12:35:27  ERROR     (not found in dictionary)
```

I'm probably missing something simple, but could someone please give me a point in the right direction?

Thanks,
Nick
[freeDiameter.conf.txt](https://github.com/freeDiameter/freeDiameter/files/8718276/freeDiameter.conf.txt)
[rt_default.conf.txt](https://github.com/freeDiameter/freeDiameter/files/8718280/rt_default.conf.txt)

**Comment by 0-wiz-0** [comment]
Have you read all of the comments at the top of the doc/rt_default_conf.sample file?
E.g. if you set Destination-Host, it will be considered first.

**Comment by nickvsnetworking** [comment]
Thanks, dropping the Destination Host entirely allowed the routing to work, and I've been able to route the traffic based on username as I'd hoped,[ I've updated the docs to include an example of routing based on Username as well.](https://github.com/freeDiameter/freeDiameter/pull/33)

Thanks for your help!
