### ISSUE TITLE
freediameter route agent

### ISSUE THREAD

**Issue by PeANuTwan** [freeDiameter/freeDiameter#46]
I would like to ask if FreeDiameter can implement a hierarchical structure for routing proxies, where higher-level proxies can forward messages to appropriate lower-level proxies or destination nodes based on global policies and routing rules. Can anyone help me with this? Thank you

**Comment by lukem** [comment]
You can use rules in `rt_default` module to change the routing rules.
Other extensions may also be useful - take a look at them in the `extensions/` directory in the source code.

**Comment by PeANuTwan** [comment]
> You can use rules in `rt_default` module to change the routing rules. Other extensions may also be useful - take a look at them in the `extensions/` directory in the source code.

Thank you very much for your reply.I use open5gs to send Diameter messages，and I would like to ask if DRA can be routed in different realm.I see in the rt_default configuration file that you can route according to the destination realm, How is the destination domain determined by the connect peer, or how do I configure the destination realm I want to send.Look forward to your favourable reply.

**Comment by lukem** [comment]
Per my first comment, the source code and documentation for the extensions can be examined to determine further details of the potential functionality, and if it's lacking functionality, the source code is available for enhancement to your own needs.

In my humble opinion, the scope of Github issues isn't really for resolving complex deployment specific support questions. Volunteer-driven open source projects such as freeDiameter that users don't even pay for generally don't have the resources to provide such level of support.
