### ISSUE TITLE
Querying Base data-type and Transformed data-type from dict_object

### ISSUE THREAD

**Issue by atari83** [freeDiameter/freeDiameter#5]
Hello!
Is it possible to get information about loaded AVP data-types ? Lets say I've used 'fd_dict_search' function on specific AVP (Session-ID) and store its data on 'dict_object' structure. Now what I need to do is to extract the data-type information from it. For instance (ex: Session-ID): Base data-type: AVP_TYPE_OCTETSTRING, Transformed data-type; UTF8String.

I tried to printed out dict_object related variables :
struct dict_object * pObj;
// fd_dict_search ..
std::cout << pObj->data.type.type_base << ", " << pObj->data.type.type_name << std::endl;

But it only prints AVP_CODE, AVP_NAME.

Thanks,

**Comment by lukem** [comment]
Try `fd_dict_getval()` into a `struct dict_avp_data`.

See <freeDiameter/libfdproto.h> for the declarations and examples in comments. and grep the source for more examples.

**Comment by atari83** [comment]
Awesome! Thank you Luke :)
