### ISSUE TITLE
URL www.freediameter.net is down

### ISSUE THREAD

**Issue by saurabhsaxena2779** [freeDiameter/freeDiameter#63]
The URL is inaccessible from any device in India. Kindly bring it up. I have already written to help@freediameter.net the mail has not yet been delivered.

**Comment by sdecugis** [comment]
Hello, thank you for the notice. The server is down indeed. I will contact them but it will take some time. The source code is still available though; if you need some information let me know.

**Comment by saurabhsaxena2779** [comment]
Yes i do need the information regarding the configuration of the clien and
server. I am unable to access those pages, kindly send me a pdf manual if
you have. I am under a deadline.

Many Thanks Indeed.
