### ISSUE TITLE
Question about incoming request processing

### ISSUE THREAD

**Issue by imperituroard** [freeDiameter/freeDiameter#67]
I am currently writing an application for processing incoming requests.
I figured out the response message, I can edit the response AVPs as I need.
But it is unclear how to go through all the AVPs of the incoming request to process them.
Moreover, it is not searching for a specific AVP in the query using the fd_msg_search_avp function, but
processing all AVPs in the query with a loop. To begin with, at least just output their value to the
debug log. I need extract AVP name and AVP value.
Can anyone help with this?

**Comment by sdecugis** [comment]
Hi, you can use the fd_msg_browse function for this purpose.
Check for example this code for example how to use it to go through the full message: https://github.com/freeDiameter/freeDiameter/blob/master/extensions/rt_rewrite/rt_rewrite.c#L122

Note that if you just want to dump message to the log, fd_msg_dump probably can help already.

BR
Seb

**Comment by imperituroard** [comment]
> Hi, you can use the fd_msg_browse function for this purpose. Check for example this code for example how to use it to go through the full message: https://github.com/freeDiameter/freeDiameter/blob/master/extensions/rt_rewrite/rt_rewrite.c#L122
> 
> Note that if you just want to dump message to the log, fd_msg_dump probably can help already.
> 
> BR Seb

Cool. Thanks a lot. All works.
